# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{oughtve}
  s.version = "106.f8221667"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eero Saynatkari"]
  s.date = %q{2010-01-15}
  s.default_executable = %q{oughtve}
  s.description = %q{Command-line tool for notes associated by filesystem location.}
  s.email = %q{oughtve@projects.kittensoft.org}
  s.executables = ["oughtve"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "Rakefile",
     "bin/oughtve",
     "doc/HOWTO.using",
     "doc/LICENCE",
     "doc/README.markdown",
     "doc/TODO",
     "lib/oughtve.rb",
     "lib/oughtve/chapter.rb",
     "lib/oughtve/database.rb",
     "lib/oughtve/errors.rb",
     "lib/oughtve/options.rb",
     "lib/oughtve/tangent.rb",
     "lib/oughtve/verse.rb",
     "setup.rb",
     "spec/bootstrap_creates_db_spec.rb",
     "spec/bootstrap_creates_default_tangent_spec.rb",
     "spec/bootstrap_raises_if_db_exists_spec.rb",
     "spec/chapter_spec.rb",
     "spec/delete_spec.rb",
     "spec/list_spec.rb",
     "spec/scribe_spec.rb",
     "spec/show_spec.rb",
     "spec/spec.rb",
     "spec/spec_helper.rb",
     "spec/strike_spec.rb",
     "spec/tangent_locating_spec.rb",
     "spec/tangent_spec.rb"
  ]
  s.homepage = %q{http://github.com/rue/oughtve}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Command-line tool for notes associated by filesystem location.}
  s.test_files = [
    "spec/bootstrap_creates_db_spec.rb",
     "spec/bootstrap_creates_default_tangent_spec.rb",
     "spec/bootstrap_raises_if_db_exists_spec.rb",
     "spec/chapter_spec.rb",
     "spec/delete_spec.rb",
     "spec/list_spec.rb",
     "spec/scribe_spec.rb",
     "spec/show_spec.rb",
     "spec/spec.rb",
     "spec/spec_helper.rb",
     "spec/strike_spec.rb",
     "spec/tangent_locating_spec.rb",
     "spec/tangent_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dm-core>, [">= 0.10.2"])
      s.add_runtime_dependency(%q<data_objects>, [">= 0.10.1"])
      s.add_runtime_dependency(%q<do_sqlite3>, [">= 0.10.1"])
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
    else
      s.add_dependency(%q<dm-core>, [">= 0.10.2"])
      s.add_dependency(%q<data_objects>, [">= 0.10.1"])
      s.add_dependency(%q<do_sqlite3>, [">= 0.10.1"])
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
    end
  else
    s.add_dependency(%q<dm-core>, [">= 0.10.2"])
    s.add_dependency(%q<data_objects>, [">= 0.10.1"])
    s.add_dependency(%q<do_sqlite3>, [">= 0.10.1"])
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
  end
end

